---
- name: Recargar orquestación Docker en la nueva versión
  shell: docker compose --env-file .env.local -p barcelonaxplorer down && docker compose --env-file .env.local -p barcelonaxplorer up -d --build --remove-orphans
  args:
    chdir: "{{ ansistrano_deploy_to }}/current"
