---
- name: Despliegue PWA BarcelonaXplorer
  hosts: nodos_pro
  gather_facts: false
  vars:
    ansistrano_deploy_from: "../src/"
    # Ruta en el PC 11 donde se construirá la estructura (releases, shared, current)
    ansistrano_deploy_to: "/home/racso/Despliegues/BarcelonaXplorer"
    ansistrano_deploy_via: "rsync"
    ansistrano_keep_releases: 3
    ansistrano_shared_files:
      - .env.production
    # Llama al hook de Docker justo después de actualizar el enlace simbólico
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/hooks/after_symlink.yml"
  pre_tasks:
    - name: Asegurar existencia del directorio shared en el Nodo 11
      ansible.builtin.file:
        path: "{{ ansistrano_deploy_to }}/shared"
        state: directory
        mode: '0755'

    - name: Asegurar existencia del directorio lancedb_data para persistencia vectorial (UID 1001)
      ansible.builtin.file:
        path: "{{ ansistrano_deploy_to }}/lancedb_data"
        state: directory
        mode: '0777'

    - name: Transferir automáticamente .env.production a shared
      ansible.builtin.copy:
        src: "../src/.env.production"
        dest: "{{ ansistrano_deploy_to }}/shared/.env.production"
        mode: '0600'
  roles:
    - ansistrano.deploy
